### ISSUE TITLE
Do not  auto bootstrap in every command

### ISSUE THREAD

**Issue by miguelandres** [d12frosted/dotbot-brew#20]

**Comment by miguelandres** [comment]
The bootstrap process takes a while and most of the time is not needed, I have several brew files in separate steps, and thus running both bootstraps becomes much slower, maybe have a separate directive for bootstraps?

**Comment by d12frosted** [comment]
I think it should bootstrap itself each time you execute something. As far as I understand, there is no problem with `_bootstrap_brew`, as it simply does `hash brew` (not the best way to check if `brew` is installed, but it's irrelevant) or install `brew`. If this step takes more than a second, then it's a bug and we need to investigate.

So I suspect the cultprit here is `_bootstrap_cask` as it unconditionally runs `brew tap caskroom/cask`. I would rather improve that instead of moving bootstraping to seaprate directive.
