### ISSUE TITLE
Add check for macOS

### ISSUE THREAD

**Issue by cupcakearmy** [d12frosted/dotbot-brew#37]
Hey there, thanks for the amazing project!

Is there any way to check for macos? otherwise the plugin fails on other systems. An easy way is to do simply a call from python and check `uname -s` and check if its `darwin`.

Otherwise maybe some docs on how to use it only on macOS
https://github.com/cupcakearmy/dotfiles/blob/7b44b3e31b5a54ee3e20b6dcf1a4a3a6e8f79989/install#L15-L19

Any thoughts?

**Comment by d12frosted** [comment]
Hey,

I am amazed that someone still uses this plugin.

Theoretically it should work on Linux as well, but I have never tested it. From your comment I guess it doesn't.  Or maybe you are running on Windows?

IMHO, `dotbot` should provide a way to conditionally enable plugin. Otherwise every plugin author will solve this on their own, potentially being not consistent with each other. I skimmed through documentation and could not find a way to do it. There is `if` directive for `shell` plugin.

**Comment by cupcakearmy** [comment]
xD Yes it's quite useful! 

I agree that it should be more of a dotbot thing, Will close it then :) I can comment it out if its not macos.

Linux fails, thats how i noticed :) don't have win.
