### ISSUE TITLE
Python Version Issue - Typing Not Allowed

### ISSUE THREAD

**Issue by mattdaviscodes** [d12frosted/dotbot-brew#40]
I think the code that gets executed when running the install script runs under python 2.7. It does on my machine, at least, and I'm not sure how to change that. 

```zsh
8:35:56 [.dotfiles] (master) % ./install
Traceback (most recent call last):
  File "/Users/mattdavis/.dotfiles/dotbot/bin/dotbot", line 45, in <module>
    main()
  File "/Users/mattdavis/.dotfiles/dotbot/bin/dotbot", line 42, in main
    dotbot.cli.main()
  File "/Users/mattdavis/.dotfiles/dotbot/dotbot/cli.py", line 132, in main
    module.load(abspath)
  File "/Users/mattdavis/.dotfiles/dotbot/dotbot/util/module.py", line 10, in load
    plugin = load_module(module_name, path)
  File "/Users/mattdavis/.dotfiles/dotbot/dotbot/util/module.py", line 33, in load_module
    return imp.load_source(module_name, path)
  File "/Users/mattdavis/.dotfiles/dotbot-brew/brew.py", line 13
    _directives: Mapping[str, Callable] = {}
               ^
SyntaxError: invalid syntax
```

Line 13 of `brew.py` is this type stuff. Hadn't seen that in python before, but I guess it's valid in 3.x.

```python3
_directives: Mapping[str, Callable] = {}
```

If I print `sys.version` from `dotbot/bin/dotbot`, I see this.

```zsh
2.7.16 (default, Sep  6 2021, 07:39:44) 
[GCC Apple LLVM 12.0.5 (clang-1205.0.19.59.6) [+internal-os, ptrauth-isa=deploy
```

Any thoughts here? I'd like to use your plugin, but something's wrong.

**Comment by d12frosted** [comment]
Hello @mattdaviscodes 

I would love to have an answer for you, but honestly, I just don't know how to help. This is the only time I coded in Python, so I simply don't know this language and can't comment on differences between Python 2 and Python 3. And also, I am not using dotbot for many years, so I can't even test it. I am just trying to keep this project alive since there are users. I am definitely looking for a (co-)maintainer, because this project needs some love. I can help with reviews and directions for project evolution.

> Hadn't seen that in python before, but I guess it's valid in 3.x.

This sounds like you have more experience in Python than me :)

**Comment by mattdaviscodes** [comment]
@d12frosted 

No problem. I understand that this package isn't your focus. Good luck in finding a maintainer!

**Comment by d12frosted** [comment]
@mattdaviscodes thank you for understanding! I hope you'll figure that out.
